[package]
name = "jcoat"
version = "0.1.0"
authors = ["bharathappali <bharath.appali@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "2.33.0", features = ["yaml"] }

[profile.release]
opt-level = 3
